class TestDataHelper:
    def __init__(self, cur):
        self.cur = cur

    # create a test formula in nominal case
    # returns the test data table names (excluding tables generated by pg_formulas)
    def create_tables(self, kind, id, create_formula=True) -> list[str]:
        match kind:
            case 'revdate':
                self.cur.execute("drop table if exists customer cascade;");
                self.cur.execute("create table customer (id SERIAL PRIMARY KEY, name text, last_modified timestamp default null);")
                if (create_formula):
                    self.cur.execute(f"call pgf_{kind}(%s, 'customer', 'last_modified')", (id,))
                res = ['customer']
            
            case 'count':
                self.cur.execute("drop table if exists invoice cascade;");
                self.cur.execute("drop table if exists customer cascade;");
                self.cur.execute("create table customer (id int PRIMARY KEY, name text, invoice_count int default 0);")
                self.cur.execute("create table invoice(id int PRIMARY KEY, name text, customer_id int references customer(id));")
                if (create_formula):
                    self.cur.execute(f"call pgf_{kind}(%s, 'customer', 'id', 'invoice_count', 'invoice', 'customer_id');", (id,))
                res = ['invoice', 'customer']
            
            case 'sum':
                self.cur.execute("drop table if exists invoice cascade;");
                self.cur.execute("drop table if exists customer cascade;");
                self.cur.execute(f"create table customer (id int PRIMARY KEY, name text, {kind}_amount numeric default 0);")
                self.cur.execute("create table invoice(id int PRIMARY KEY, name text, customer_id int references customer(id), amount numeric);")
                if (create_formula):
                    self.cur.execute(f"call pgf_{kind}(%s, 'customer', 'id', '{kind}_amount', 'invoice', 'customer_id', 'amount');", (id,))
                res = ['invoice', 'customer']
            
            case 'min' | 'max':
                self.cur.execute("drop table if exists invoice cascade;");
                self.cur.execute("drop table if exists customer cascade;");
                self.cur.execute(f"create table customer (id int PRIMARY KEY, name text, {kind}_amount numeric default NULL);")
                self.cur.execute("create table invoice(id int PRIMARY KEY, name text, customer_id int references customer(id), amount numeric);")
                if (create_formula):
                    self.cur.execute(f"call pgf_{kind}(%s, 'customer', 'id', '{kind}_amount', 'invoice', 'customer_id', 'amount');", (id,))
                res = ['invoice', 'customer']

            case 'id_of_min' | 'id_of_max':
                self.cur.execute("drop table if exists invoice cascade;");
                self.cur.execute("drop table if exists customer cascade;");
                self.cur.execute(f"create table customer (id int PRIMARY KEY, name text, {kind}_amount int default NULL);")
                self.cur.execute("create table invoice(id int PRIMARY KEY, name text, customer_id int references customer(id), amount numeric);")
                if (create_formula):
                    self.cur.execute(f"call pgf_{kind}(%s, 'customer', 'id', '{kind}_amount', 'invoice', 'id', 'customer_id', 'amount');", (id,))
                res = ['invoice', 'customer']
            
            case 'array_agg':
                self.cur.execute("drop table if exists invoice cascade;");
                self.cur.execute("drop table if exists customer cascade;");
                self.cur.execute(f"create table customer (id int PRIMARY KEY, name text, invoice_names text[] default NULL);")
                self.cur.execute("create table invoice(id int PRIMARY KEY, name text, customer_id int references customer(id), visible boolean);")
                if (create_formula):
                    self.cur.execute(f"call pgf_{kind}(%s, 'customer', 'id', 'invoice_names', 'invoice', 'customer_id', 'name');", (id,))
                res = ['invoice', 'customer']
            
            case 'minmax_table':
                self.cur.execute("drop table if exists customer cascade;");
                self.cur.execute("drop table if exists invoice cascade;");
                self.cur.execute(f"drop table if exists agg cascade;");
                self.cur.execute("create table invoice(id int PRIMARY KEY, name text, customer_id int, country text, amount NUMERIC(10, 2));")
                if (create_formula):
                    self.cur.execute(f"call pgf_{kind}(%s, 'invoice', 'id', 'amount', jsonb_build_object('agg_table', 'agg', 'group_by_column', ARRAY['customer_id', 'country']));", (id,))
                res = ['invoice', 'customer']
            
            case 'inheritance_table':
                self.cur.execute("drop table if exists bike cascade;");
                self.cur.execute("drop table if exists car cascade;");
                self.cur.execute("drop table if exists vehicle cascade;");
                self.cur.execute("create table bike(id int, common_attribute1 TEXT, bike_attribute1 TEXT)")
                self.cur.execute("create table car(id int, common_attribute1 TEXT, car_attribute1 DECIMAL)")
                if (create_formula):
                    self.cur.execute(f"call pgf_{kind}(%s, 'vehicle', ARRAY['bike', 'car'], 'SUB_TO_BASE')", (id,));
                res = ['bike', 'car', 'vehicle']
            
            case 'audit_table':
                self.cur.execute("drop table if exists customer cascade;")
                self.cur.execute("create table customer(id serial primary key, name text, value int);")
                if (create_formula):
                    self.cur.execute(f"call pgf_{kind}(%s, 'customer_events', ARRAY['customer']);", (id,))
                res = ['customer']

            case 'sync':
                self.cur.execute("drop table if exists customer cascade;")
                self.cur.execute("create table customer(id text, customer_name text, name text);")
                if (create_formula):
                    self.cur.execute(f"call pgf_{kind}(%s, 'customer', 'name', 'customer_name');", (id,))
                res = ['customer']
            
            case 'tree_level':
                self.cur.execute("drop table if exists node cascade;");
                self.cur.execute("create table node(id int PRIMARY KEY, name text, parent_id int, level int);")
                if (create_formula):
                    self.cur.execute(f"call pgf_{kind}(%s, 'node', 'id', 'parent_id', 'level');", (id,))
                res = ['node']

            case 'tree_closure_table':
                self.cur.execute("drop table if exists node cascade;");
                self.cur.execute("drop table if exists node_closure cascade;");
                self.cur.execute("create table node(id int PRIMARY KEY, name text, parent_id int);")
                if (create_formula):
                    self.cur.execute(f"call pgf_{kind}(%s, 'node', 'id', 'parent_id');", (id,))
                res = ['node']
            
            case 'intersect_table':
                self.cur.execute("drop table if exists a cascade;");
                self.cur.execute("drop table if exists b cascade;");
                self.cur.execute("drop table if exists c cascade;");
                self.cur.execute("drop table if exists intersect_table cascade;");
                self.cur.execute("create table a(column1 text, column2 int, column3 text default '');")
                self.cur.execute("create table b(column1 text, column2 int, column3 text default '');")
                self.cur.execute("create table c(column1 text, column2 int, column3 text default '');")
                if (create_formula):
                    self.cur.execute(f"call pgf_{kind}(%s, ARRAY['a', 'b', 'c'], ARRAY['column1', 'column2'], 'intersect_table')", (id,))
                res = ['a', 'b', 'c']
            
            case 'union_table':
                self.cur.execute("drop table if exists a cascade;");
                self.cur.execute("drop table if exists b cascade;");
                self.cur.execute("drop table if exists c cascade;");
                self.cur.execute("drop table if exists union_table cascade;");
                self.cur.execute("create table a(column1 text, column2 int, column3 text default '');")
                self.cur.execute("create table b(column1 text, column2 int, column3 text default '');")
                self.cur.execute("create table c(column1 text, column2 int, column3 text default '');")
                if (create_formula):
                    self.cur.execute(f"call pgf_{kind}(%s, ARRAY['a', 'b', 'c'], ARRAY['column1', 'column2'], 'union_table')", (id,))
                res = ['a', 'b', 'c']
            
            case _:
                raise ValueError(f"Invalid Argument: {kind}")
        self.cur.execute("commit");
        return res
    